### ISSUE TITLE
onParentExpanded方法里的byUser参数异常

### ISSUE THREAD

**Issue by dakun666** [huajianjiang/ExpandableRecyclerView#2]
你好，我在使用中发现一个问题，就是在展开的回调里，也就是onParentExpanded方法里的byUser参数始终为false。我现在想要判断是否是用户点击打开，实现展开时自动跳转到展开项底部的需求，望解答如何区分！拜谢

**Comment by progratient** [comment]
Hi, @dakun666  谢谢你提交的 issue

现在已经修复了该回调相关的问题，还没提交到 `Maven` 上。
如果你想在可展开的父列表项展开的时候自动滑动到该项的底部来展示完全内容，你可以在监听器的回调里调用 `RecyclerView` 相关滚动接口来处理, 比如 `scrollToPosition (int position)` 传递 parent 的 adapterPosition +  该 parent 所含有的 child 的数量 的值进去就可以，亲测可行:
```java
 if (byUser) {
     int scrollToPos = pvh.getAdapterPosition() + ((MyParent) pvh.getParent()).getChildCount();
     rv.scrollToPosition(scrollToPos);
 }
```

**Comment by dakun666** [comment]
谢谢解答！我的解决方法是
```
Data data = (Data) getDataList().get(position);
rv.scrollToPosition(pvh.getLayoutPosition() + data.getChildren().size());
```
也是可以用的。
你的库很棒！我已经用到了我的项目中，有什么问题和建议我会发上来的。
再次感谢
